# Generated by Django 2.2.5 on 2019-09-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_uno', models.CharField(max_length=200, verbose_name='pregunta uno')),
                ('respuesta_uno_a', models.CharField(max_length=200, verbose_name='respuesta uno a')),
                ('respuesta_uno_b', models.CharField(max_length=200, verbose_name='respuesta uno b')),
                ('respuesta_uno_c', models.CharField(max_length=200, verbose_name='respuesta uno c')),
                ('respuesta_uno_d', models.CharField(max_length=200, verbose_name='respuesta uno d')),
                ('respuesta_correcta_uno', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1)),
                ('pregunta_dos', models.CharField(max_length=200, verbose_name='pregunta dos')),
                ('respuesta_dos_a', models.CharField(max_length=200, verbose_name='respuesta dos a')),
                ('respuesta_dos_b', models.CharField(max_length=200, verbose_name='respuesta dos b')),
                ('respuesta_dos_c', models.CharField(max_length=200, verbose_name='respuesta dos c')),
                ('respuesta_dos_d', models.CharField(max_length=200, verbose_name='respuesta dos d')),
                ('respuesta_correcta_dos', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1)),
                ('pregunta_tres', models.CharField(max_length=200, verbose_name='pregunta tres')),
                ('respuesta_tres_a', models.CharField(max_length=200, verbose_name='respuesta tres a')),
                ('respuesta_tres_b', models.CharField(max_length=200, verbose_name='respuesta tres b')),
                ('respuesta_tres_c', models.CharField(max_length=200, verbose_name='respuesta tres c')),
                ('respuesta_tres_d', models.CharField(max_length=200, verbose_name='respuesta tres d')),
                ('respuesta_correcta_tres', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1)),
                ('pregunta_cuatro', models.CharField(max_length=200, verbose_name='pregunta cuatro')),
                ('respuesta_cuatro_a', models.CharField(max_length=200, verbose_name='respuesta cuatro a')),
                ('respuesta_cuatro_b', models.CharField(max_length=200, verbose_name='respuesta cuatro b')),
                ('respuesta_cuatro_c', models.CharField(max_length=200, verbose_name='respuesta cuatro c')),
                ('respuesta_cuatro_d', models.CharField(max_length=200, verbose_name='respuesta cuatro d')),
                ('respuesta_correcta_cuatro', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1)),
                ('pregunta_cinco', models.CharField(max_length=200, verbose_name='pregunta cinco')),
                ('respuesta_cinco_a', models.CharField(max_length=200, verbose_name='respuesta cinco a')),
                ('respuesta_cinco_b', models.CharField(max_length=200, verbose_name='respuesta cinco b')),
                ('respuesta_cinco_c', models.CharField(max_length=200, verbose_name='respuesta cinco c')),
                ('respuesta_cinco_d', models.CharField(max_length=200, verbose_name='respuesta cinco d')),
                ('respuesta_correcta_cinco', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1)),
            ],
        ),
    ]
